version: "3.8"
services:
    golang_echo_api:
        container_name: golang_echo_api
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.docker
        networks:
            - golang_echo_network
        depends_on:
            - golang_echo_mongo
        restart: "on-failure"

    golang_echo_mongo:
        image: mongo:latest
        container_name: golang_echo_mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: golang_echodb
        networks:
            - golang_echo_network
        ports:
            - "27017:27017"
        volumes:
            - ./mongo:/data/db

    golang_echo_nginx:
        build:
            context:  ./nginx
            dockerfile: Dockerfile
        ports:
            - "5001:80"
        networks:
            - golang_echo_network
        depends_on:
            - golang_echo_api
        links:
            - golang_echo_api:golang_echo_api

volumes:
    mongo:
networks:
    golang_echo_network:
        driver: bridge
