version: "3.7"
services:
    golang_echo_api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080


    golang_echo_mongo:
        image: mongo:3.6
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: golang_echodb
        ports:
            - 27017:27017
        volumes:
            - ./mongo:/data/db

volumes:
    mongo: