global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: golang_echo_api
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["golang_echo_api:5050"]

